### PR TITLE
Sasserides-A updates

### PR DESCRIPTION
**Pull request by martinling**
This PR updates the Sasserides-A board design.

image

Key changes are as follows:

- A [CDCV304](https://www.ti.com/lit/ds/symlink/cdcv304.pdf) clock buffer IC is added at the base of the CLK test pin in order to reduce loading of the EUT clock.
- The J1 pin header footprint has been updated to a keyed shrouded type, with orientation indicated on silkscreen.
- The two LED groups have been moved further apart to make them more visually distinct.
- Routing has been revised to run signals on the top layer only with a solid ground plane on the back side.

This version is electrically compatible with Sasserides-A r1.0.0. The Sasserides-B board is unchanged and remains at r1.0.0.

### CODE REVIEW

**Comment by mossmann** [comment]
ERC gives me a warning: `The current configuration does not include the library 'tycho'`

Is there an uncommitted sym-lib-table perhaps?

**Review by mossmann — CHANGES_REQUESTED** [review]
ERC gives me a warning: The current configuration does not include the library 'tycho'

Is there an uncommitted sym-lib-table perhaps?

Otherwise this looks great!

**Comment by martinling** [comment]
Added the necessary symbol library table, a series resistor at the clock buffer output, and a pulldown at the clock buffer input (to prevent it floating when the EUT is unpowered).

**Review by mossmann — CHANGES_REQUESTED** [review]
There is a fairly innocuous schematic parity error with the orientation of R14. I think the easiest way to correct it is to flip the part with 'y' in the schematic and then update the layout from the schematic. I would like this to be fixed because it could lead to a worse error in a future rev. Otherwise I am very pleased with the updates.

**Review by mossmann — APPROVED** [review]
Beautiful! Thank you!

**Pull request merged**
